title: <p align="center"> Manish </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/manish-4294055a/">LinkedIn</a> |
  <a href="https://github.com/ManishKhatri29031987">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
   <br>
  </p>



theme: jekyll-theme-minimal
